---

- name: "Look up Nexus URL"
  command: >
    oc get route {{ nexus_name | default('nexus') }} -n {{ nexus_namespace }} -o custom-columns=ROUTE:.spec.host --no-headers
  register: nexus_url_result
  when:
  - nexus_url is not defined or nexus_url|trim == ''
- name: "Look up Nexus tls settings"
  command: >
    oc get route {{ nexus_name | default('nexus') }} -n {{ nexus_namespace }} -o custom-columns=ROUTE:.spec.tls --no-headers
  register: tls_result
  when:
  - nexus_url is not defined or nexus_url|trim == ''

- name: "Set http_protocol to http by default"
  set_fact:
    http_protocol: "http"
  when:
  - nexus_url is not defined
- name: "Set http_protocol for nexus_url"
  set_fact:
    http_protocol: "https"
  when:
  - nexus_url is not defined
  - "'<none>' not in tls_result.stdout" 
- name: "Set nexus_url Result"
  set_fact:
    nexus_url: "{{http_protocol}}://{{ nexus_url_result.stdout }}"
  when:
  - nexus_url is not defined or nexus_url|trim == ''

- name: "Ensure Nexus is available before attempting to communicate"
  include_tasks: wait-for-nexus.yml

- name: "Configure Repos"
  include_tasks: configure-repos.yml
  with_items:
  - "{{ nexus_repos | default([]) }}"

